/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-container": "#6063ee",
        "surface": "var(--color-surface)",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "outline": "#767586",
        "on-secondary-container": "#fffbff",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#b55d00",
        "surface-variant": "var(--color-surface-container-highest)",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb783",
        "surface-bright": "var(--color-surface)",
        "on-primary-container": "#fffbff",
        "secondary": "#8127cf",
        "on-tertiary-fixed-variant": "#703700",
        "error": "#ba1a1a",
        "background": "var(--color-background)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-tint": "#494bd6",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "tertiary-fixed": "#ffdcc5",
        "surface-dim": "var(--color-surface-container-high)",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#301400",
        "outline-variant": "#c7c4d7",
        "primary-fixed": "#e1e0ff",
        "on-background": "var(--color-on-background)",
        "surface-container": "var(--color-surface-container)",
        "secondary-fixed": "#f0dbff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "primary": "#4648d4",
        "on-surface": "var(--color-on-surface)",
        "tertiary": "#904900",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ddb7ff",
        "inverse-on-surface": "#eff1f3",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-container": "#9c48ea",
        "error-container": "#ffdad6",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed": "#07006c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "20px",
        container_max: "1280px",
        sidebar_width: "240px",
        sidebar_collapsed: "72px",
        navbar_height: "64px",
        base: "8px",
      },
      fontFamily: {
        h1: ["Poppins", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        h2: ["Poppins", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        h3: ["Poppins", "sans-serif"],
      },
      fontSize: {
        h1: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h2: [
          "24px",
          { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        h3: ["20px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
